version: "2"

services:
  parmahan:
    image: parmahan:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "parmahan"
    working_dir: /var/www
    command: php -S 0.0.0.0:8080 -t public
    env_file: .env
    ports:
      - "8080:8080"
    volumes:
      - .:/var/www
    networks:
      - default
      - bridge-network
networks:
  default:
    driver: bridge
  bridge-network:
    external: true